# Generated by Django 4.1 on 2023-01-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("run", "0004_run_notes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="event",
            unique_together={("location", "number")},
        ),
    ]
