# Generated by Django 4.1 on 2023-01-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("run", "0005_alter_event_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="event",
            unique_together=set(),
        ),
    ]
