# Generated by Django 4.1 on 2023-02-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("run", "0006_alter_event_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="number",
            new_name="number1",
        ),
    ]
