# Generated by Django 4.1 on 2023-02-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("run", "0008_remove_event_number1_event_number2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="number2",
        ),
        migrations.AddField(
            model_name="event",
            name="number",
            field=models.CharField(default="#-666", max_length=100),
        ),
        migrations.AlterField(
            model_name="timings",
            name="runnerClub",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="timings",
            name="runnerGroup",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="timings",
            name="runnerTime",
            field=models.CharField(max_length=100),
        ),
    ]
