# Generated by Django 4.1 on 2023-02-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("run", "0009_remove_event_number2_event_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="number",
        ),
    ]
