# Generated by Django 4.1 on 2023-02-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("run", "0010_remove_event_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="number",
            field=models.CharField(default="#", max_length=200),
        ),
    ]
